require("config.options")
require("config.remaps")

require("config.lazy")

require("plugins.colorscheme-config")
require("plugins.just-setups-config")
require("plugins.treesitter-config")
require("plugins.gitsigns-config")
require("plugins.lsp-config")
require("plugins.file-tree-config")
require("plugins.fugitive-config")
require("plugins.telescope-config")
require("plugins.spectre-config")
require("plugins.toggleterm-config")
require("plugins.statusline-config")
